### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by YZSyangzhaoshuo** [oceanbase/obdiag#212]
### Describe the bug

024-05-17 11:14:06.978 [XNIO-1 task-4] INFO  c.alipay.ocp.core.obsdk.connector.ConnectTemplate - [obsdk] queryForObject sql:[select/*+ READ_CONSISTENCY(WEAK) QUERY_TIMEOUT(60000000) */ tenant_id from gv$tenant where  tenant_name = ? limit 1],args: [[yh_01]]
2024-05-17 11:14:06.984 [XNIO-1 task-4] ERROR com.oceanbase.service.impl.SqlReviewServiceImpl - sql review error: 
java.lang.NullPointerException: null
        at com.oceanbase.utils.MysqlParseUtils$15.visitColumn_ref(MysqlParseUtils.java:1078)
        at com.oceanbase.sqlparser.mysql.sql.OBParser$Column_refContext.accept(OBParser.java:1979)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.oceanbase.sqlparser.mysql.sql.OBParserBaseVisitor.visitSimple_expr(OBParserBaseVisitor.java:140)
        at com.oceanbase.sqlparser.mysql.sql.OBParser$Simple_exprContext.accept(OBParser.java:3247)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.oceanbase.sqlparser.mysql.sql.OBParserBaseVisitor.visitBit_expr(OBParserBaseVisitor.java:133)
        at com.oceanbase.sqlparser.mysql.sql.OBParser$Bit_exprContext.accept(OBParser.java:3067)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.oceanbase.sqlparser.mysql.sql.OBParserBaseVisitor.visitPredicate(OBParserBaseVisitor.java:126)
        at com.oceanbase.sqlparser.mysql.sql.OBParser$PredicateContext.accept(OBParser.java:2891)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.oceanbase.sqlparser.mysql.sql.OBParserBaseVisitor.visitBool_pri(OBParserBaseVisitor.java:119)
        at com.oceanbase.sqlparser.mysql.sql.OBParser$Bool_priContext.accept(OBParser.java:2720)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.oceanbase.sqlparser.mysql.sql.OBParserBaseVisitor.visitExpr(OBParserBaseVisitor.java:147)
        at com.oceanbase.sqlparser.mysql.sql.OBParser$ExprContext.accept(OBParser.java:3543)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.oceanbase.sqlparser.mysql.sql.OBParserBaseVisitor.visitExpr(OBParserBaseVisitor.java:147)
        at com.oceanbase.sqlparser.mysql.sql.OBParser$ExprContext.accept(OBParser.java:3543)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.oceanbase.sqlparser.mysql.sql.OBParserBaseVisitor.visitSimple_expr(OBParserBaseVisitor.java:140)
        at com.oceanbase.sqlparser.mysql.sql.OBParser$Simple_exprContext.accept(OBParser.java:3247)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.oceanbase.sqlparser.mysql.sql.OBParserBaseVisitor.visitBit_expr(OBParserBaseVisitor.java:133)
        at com.oceanbase.sqlparser.mysql.sql.OBParser$Bit_exprContext.accept(OBParser.java:3067)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.oceanbase.sqlparser.mysql.sql.OBParserBaseVisitor.visitPredicate(OBParserBaseVisitor.java:126)
        at com.oceanbase.sqlparser.mysql.sql.OBParser$PredicateContext.accept(OBParser.java:2891)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.oceanbase.sqlparser.mysql.sql.OBParserBaseVisitor.visitBool_pri(OBParserBaseVisitor.java:119)
        at com.oceanbase.sqlparser.mysql.sql.OBParser$Bool_priContext.accept(OBParser.java:2720)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.oceanbase.sqlparser.mysql.sql.OBParserBaseVisitor.visitExpr(OBParserBaseVisitor.java:147)
        at com.oceanbase.sqlparser.mysql.sql.OBParser$ExprContext.accept(OBParser.java:3543)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at com.oceanbase.sqlparser.mysql.sql.OBParserBaseVisitor.visitExpr(OBParserBaseVisitor.java:147)
        at com.oceanbase.sqlparser.mysql.sql.OBParser$ExprContext.accept(OBParser.java:3543)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at com.oceanbase.utils.MysqlParseUtils.getColumnWithInTooManyItems(MysqlParseUtils.java:1102)
        at com.oceanbase.utils.MysqlParseUtils.lambda$null$22(MysqlParseUtils.java:1052)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.oceanbase.utils.MysqlParseUtils.lambda$getColumnWithInTooManyItems$23(MysqlParseUtils.java:1052)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.oceanbase.utils.MysqlParseUtils.getColumnWithInTooManyItems(MysqlParseUtils.java:1049)
        at com.oceanbase.advisor.SQLReviewer.MysqlReviewer.inContainsTooManyItems(MysqlReviewer.java:204)
        at com.oceanbase.advisor.SQLReviewer.MysqlReviewer.ruleChecker(MysqlReviewer.java:70)
        at com.oceanbase.service.impl.SqlReviewServiceImpl.mysqlReviewer(SqlReviewServiceImpl.java:180)
        at com.oceanbase.service.impl.SqlReviewServiceImpl.sqlReviewFromText(SqlReviewServiceImpl.java:144)
        at com.oceanbase.service.impl.SqlReviewServiceImpl.sqlReview(SqlReviewServiceImpl.java:130)
        at com.oceanbase.controller.SqlReviewController.sqlReview(SqlReviewController.java:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:517)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
        at java.lang.Thread.run(Thread.java:748)
2024-05-17 11:14:06.984 [XNIO-1 task-4] INFO  com.oceanbase.service.impl.SqlReviewServiceImpl - sql review result [SqlReviewResult(sqlText=null, success=false, suggestions=null, failedMessage=null)]

### Environment

V4.2.0_BP

### Fast reproduce steps

SQL Review 功能报错

**Comment by Teingi** [comment]
SQL Review这个目前是单独的工具，用Java写的，叫做SQL Diagnoser，后期不会再迭代了。其功能会在obdiag 上实现，已经在开发中，版本2.3.0.概要设计：https://oceanbase.yuque.com/org-wiki-obtech-vh7w9r/imzr6c/igqcmzrapk7e4hpx 计划发布时间2024年7月初
